### PR TITLE
STOR-1874: Use real HyperShift API

### PR DESCRIPTION
**Pull request by mpatlasov**
Use HyperShift HostedControlPlane type instead of Unstructured in hooks.go

@openshift/storage

### CODE REVIEW

**Comment by mpatlasov** [comment]
/hold

(need to fix unit tests)

**Comment by mpatlasov** [comment]
/unhold

(unit-tests fixed)

File: pkg/clients/builder.go [hunk 1]
```diff
@@ -75,6 +77,9 @@ func (b *Builder) BuildOrDie(ctx context.Context) *Clients {
 	controlPlaneDynamicClient := dynamic.NewForConfigOrDie(controlPlaneRestConfig)
 	controlPlaneDynamicInformers := dynamicinformer.NewFilteredDynamicSharedInformerFactory(controlPlaneDynamicClient, b.resync, b.controllerConfig.OperatorNamespace, nil)
 
+	controlPlaneHypeClient := hypextclient.NewForConfigOrDie(controlPlaneRestConfig)
+	controlPlaneHypeInformers := hypextinformers.NewFilteredSharedInformerFactory(controlPlaneHypeClient, b.resync, b.controllerConfig.OperatorNamespace, nil)
+
```
Comment (jsafrane) [inline pkg/clients/builder.go:82]: This should be initialized only on HyperShift. Otherwise the HyperShift CRDs are not in the API server and esp. the informer will log weird errors periodically.

File: pkg/driver/common/operator/hooks.go [hunk 2]
```diff
@@ -75,8 +75,9 @@ func withHyperShiftNodeSelector(c *clients.Clients) (dc.DeploymentHookFunc, []fa
 	hook := func(_ *opv1.OperatorSpec, deployment *appsv1.Deployment) error {
 		podSpec := &deployment.Spec.Template.Spec
 		// Add nodeSelector
+		genInformer, _ := c.ControlPlaneHypeInformer.ForResource(hostedControlPlaneGVR)
```
Comment (jsafrane) [inline pkg/driver/common/operator/hooks.go:78]: Use a typed lister, that's why we import the generated client.
```suggestion
		hcpLister := c.ControlPlaneHypeInformer.Hypershift().V1beta1().HostedControlPlanes().Lister()
```

File: pkg/driver/common/operator/hooks.go [hunk 3]
```diff
@@ -85,8 +86,9 @@ func withHyperShiftNodeSelector(c *clients.Clients) (dc.DeploymentHookFunc, []fa
 
 		return nil
 	}
+	genInformer, _ := c.ControlPlaneHypeInformer.ForResource(hostedControlPlaneGVR)
```
Comment (jsafrane) [inline pkg/driver/common/operator/hooks.go:89]: Again, a typed informer would be more appropriate
```suggestion
	hcpInformer := c.ControlPlaneHypeInformer.Hypershift().V1beta1().HostedControlPlanes().Informer()
```

File: pkg/driver/common/operator/hooks.go (hunk 2 above)
Comment (jsafrane) [reply pkg/driver/common/operator/hooks.go:78]: `getHostedControlPlaneNodeSelector` then gets `HostedControlPlaneLister` instead of `GenericLister`, and `getHostedControlPlane` down below does not need to retype a RuntimeObject to a `HostedControlPlane`.

File: go.mod [hunk 4]
```diff
@@ -29,88 +33,95 @@ require (
...
 )
+
+replace github.com/google/cel-go => github.com/google/cel-go v0.17.7
+
+// There is an error with newer versions of prometheus
+// vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/promlint.go:71:38: undefined: expfmt.FmtText
+replace (
+	github.com/prometheus/client_golang => github.com/prometheus/client_golang v1.18.0
+	github.com/prometheus/common => github.com/prometheus/common v0.45.0
+)
```
Comment (jsafrane) [inline go.mod:127]: This is odd. Why do you update cel-go to 0.18 above and then reset it back to 0.17.7 there? Same for prometheus libs.
I think you can try with https://github.com/openshift/csi-operator/pull/240

Comment (jsafrane) [reply go.mod:127]: We discussed it, it's inevitable to have these replaces :-(
Please rebase

**Comment by mpatlasov** [comment]
Last push rebases PR to the head of `openshift/csi-operator` master.

**Comment by Phaow** [comment]
I did some manual checks on the management cluster all driver operators and controllers works well with the pre merged build `4.17.0-0.test-2024-07-29-025914-ci-ln-6m0r8rb-latest (build 4.17,openshift/csi-operator#236)` . Also launch a [regression test ](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/ginkgo-test/260060/console) towards the pre merge build cluster, all passed.
```console
47 pass, 16 skip (20m2s)
```
